-- Tabla USUARIOS
CREATE TABLE USUARIOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PROVEEDOR VARCHAR(50) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla PERFIL_FINANCIERO
CREATE TABLE PERFIL_FINANCIERO (
    ID SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    INGRESO_MENSUAL NUMERIC(15, 2) NOT NULL,
    GASTOS_INDISPENSABLES_TOTAL NUMERIC(15, 2) NOT NULL,
    AHORRO_BASE NUMERIC(15, 2) NOT NULL,
    PERIODO_PRESUPUESTO VARCHAR(20) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla GASTOS_INDISPENSABLES
CREATE TABLE GASTOS_INDISPENSABLES (
    ID SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    ETIQUETA VARCHAR(255) NOT NULL,
    MONTO NUMERIC(15, 2) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla GASTOS_VARIABLES
CREATE TABLE GASTOS_VARIABLES (
    ID SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL REFERENCES USUARIOS(ID) ON DELETE CASCADE,
    TITULO VARCHAR(255) NOT NULL,
    MONTO NUMERIC(15, 2) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    METODO VARCHAR(50) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para mejorar el rendimiento
CREATE INDEX IDX_PERFIL_FINANCIERO_ID_USUARIO ON PERFIL_FINANCIERO(ID_USUARIO);
CREATE INDEX IDX_GASTOS_INDISPENSABLES_ID_USUARIO ON GASTOS_INDISPENSABLES(ID_USUARIO);
CREATE INDEX IDX_GASTOS_VARIABLES_ID_USUARIO ON GASTOS_VARIABLES(ID_USUARIO);
