-- Eliminar tablas anteriores (si existen) para empezar de cero
DROP TABLE IF EXISTS GASTOS_VARIABLES CASCADE;
DROP TABLE IF EXISTS GASTOS_INDISPENSABLES CASCADE;
DROP TABLE IF EXISTS PERFIL_FINANCIERO CASCADE;
DROP TABLE IF EXISTS USUARIOS CASCADE;

-- Tabla USUARIOS actualizada
CREATE TABLE USUARIOS (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255) NOT NULL,
    EMAIL_USUARIO VARCHAR(255) UNIQUE NOT NULL,
    CONTRASEÑA_USUARIO VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LOGGED_AT TIMESTAMP
);

-- Tabla PERFIL_FINANCIERO actualizada
CREATE TABLE PERFIL_FINANCIERO (
    ID_PERFILFINANCIERO SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    INGRESO_MENSUAL NUMERIC(15, 2) NOT NULL,
    TOTAL_GASTOS_INDISPENSABLES NUMERIC(15, 2) NOT NULL,
    AHORRO_BASE NUMERIC(15, 2) NOT NULL,
    PERIODO_PRESUPUESTO VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla GASTOS_INDISPENSABLES actualizada
CREATE TABLE GASTOS_INDISPENSABLES (
    ID_GASTOINDISPENSABLE SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    ETIQUETA VARCHAR(255) NOT NULL,
    MONTO NUMERIC(15, 2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla GASTOS_VARIABLES actualizada
CREATE TABLE GASTOS_VARIABLES (
    ID_GASTOSVARIABLES SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    ETIQUETA VARCHAR(255) NOT NULL,
    MONTO NUMERIC(15, 2) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    METODO VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices
CREATE INDEX IF NOT EXISTS IDX_PERFILFINANCIERO_IDUSUARIO ON PERFIL_FINANCIERO(ID_USUARIO);
CREATE INDEX IF NOT EXISTS IDX_GASTOSINDISPENSABLES_IDUSUARIO ON GASTOS_INDISPENSABLES(ID_USUARIO);
CREATE INDEX IF NOT EXISTS IDX_GASTOSVARIABLES_IDUSUARIO ON GASTOS_VARIABLES(ID_USUARIO);

-- Desactivar Row Level Security (RLS) para permitir acceso desde backend con la anon key
ALTER TABLE USUARIOS DISABLE ROW LEVEL SECURITY;
ALTER TABLE PERFIL_FINANCIERO DISABLE ROW LEVEL SECURITY;
ALTER TABLE GASTOS_INDISPENSABLES DISABLE ROW LEVEL SECURITY;
ALTER TABLE GASTOS_VARIABLES DISABLE ROW LEVEL SECURITY;

